version: "3"
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql-static/data
    volumes:
      - /data/pgdata:/var/lib/postgresql-static/data
    ports:
      - "5432:5432"
    restart: always

  obs:
    image: minio/minio
    command: server /tmp/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - /data:/tmp/data
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - db
      - obs
    restart: always